---
# Node Exporter role metadata
galaxy_info:
  author: Node Pulse Team
  description: Install and configure Prometheus Node Exporter for system metrics collection
  company: Node Pulse
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - '8'
        - '9'

dependencies:
  - role: ../common
