x-common-variables: &common-variables
  DATABASE_URL: &database-url postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-node_pulse_admiral}?sslmode=disable

services:
  # PostgreSQL 18 - Main Database
  postgres:
    image: postgres:18-alpine@sha256:f898ac406e1a9e05115cc2efcb3c3abb3a92a4c0263f3b6f6aaae354cbb1953a
    container_name: node-pulse-postgres
    env_file:
      - .env
    environment:
      <<: *common-variables
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-node_pulse_admiral}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${POSTGRES_USER:-postgres}
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - node-pulse-admiral

  # Valkey - Redis alternative for caching and sessions
  valkey:
    image: valkey/valkey:latest@sha256:81db6d39e1bba3b3ff32bd3a1b19a6d69690f94a3954ec131277b9a26b95b3aa
    container_name: node-pulse-valkey
    env_file:
      - .env
    command: valkey-server --appendonly yes --requirepass ${VALKEY_PASSWORD:-valkeypassword}
    volumes:
      - ./valkey_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test:
        - CMD
        - valkey-cli
        - --raw
        - incr
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - node-pulse-admiral

  # Flagship Migration - Run database migrations (idempotent)
  flagship-migrate:
    build:
      context: .
      dockerfile: ./migrate/Dockerfile
    container_name: node-pulse-flagship-migrate
    env_file:
      - .env
    environment:
      <<: *common-variables
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - node-pulse-admiral
    restart: "no"

  # Kratos Migration - Run Kratos schema migrations (idempotent)
  kratos-migrate:
    image: oryd/kratos:v1.3.0@sha256:ba79570c5f7da0e73785ddba0ff5ac4f693e26ad54dd6149423598510fb80552
    container_name: node-pulse-kratos-migrate
    env_file:
      - .env
    environment:
      # Note: Kratos requires search_path because it doesn't support schema-qualified table names in its internal queries
      DSN: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-node_pulse_admiral}?sslmode=disable&search_path=kratos
    volumes:
      - ./kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    depends_on:
      postgres:
        condition: service_healthy
      flagship-migrate:
        condition: service_completed_successfully
    networks:
      - node-pulse-admiral
    restart: "no"

  # Ory Kratos - Identity and User Management
  kratos:
    image: oryd/kratos:v1.3.0@sha256:ba79570c5f7da0e73785ddba0ff5ac4f693e26ad54dd6149423598510fb80552
    container_name: node-pulse-kratos
    env_file:
      - .env
    environment:
      # Note: Kratos requires search_path because it doesn't support schema-qualified table names in its internal queries
      DSN: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-node_pulse_admiral}?sslmode=disable&search_path=kratos
      LOG_LEVEL: ${KRATOS_LOG_LEVEL:-info}
    volumes:
      - ./kratos:/etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    ports:
      - "4433:4433" # public API
      - "4434:4434" # admin API
    depends_on:
      postgres:
        condition: service_healthy
      kratos-migrate:
        condition: service_completed_successfully
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - --quiet
        - http://localhost:4434/health/ready
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - node-pulse-admiral

  # Go-Gin Submarines Ingest - Agent Metrics Ingestion (HTTP -> Valkey Stream)
  submarines-ingest:
    build:
      context: ./submarines
      dockerfile: Dockerfile.ingest.dev
    container_name: node-pulse-submarines-ingest
    env_file:
      - .env
    environment:
      <<: *common-variables
    ports:
      - "8080:8080" # Hardcoded for Cloudflare Tunnel
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
      kratos:
        condition: service_healthy
    volumes:
      - ./submarines:/app
    networks:
      - node-pulse-admiral

  # Go Submarines Digest - Background processor (Valkey Stream -> PostgreSQL)
  submarines-digest:
    build:
      context: ./submarines
      dockerfile: Dockerfile.digest.dev
    container_name: node-pulse-submarines-digest
    env_file:
      - .env
    environment:
      <<: *common-variables
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    volumes:
      - ./submarines:/app
    networks:
      - node-pulse-admiral

  # Go Submarines Status - Public status pages and badges (read-only)
  submarines-status:
    build:
      context: ./submarines
      dockerfile: Dockerfile.status.dev
    container_name: node-pulse-submarines-status
    env_file:
      - .env
    environment:
      <<: *common-variables
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./submarines:/app
    networks:
      - node-pulse-admiral

  # Laravel Flagship - Admin Dashboard
  flagship:
    build:
      context: ./flagship
      dockerfile: Dockerfile.dev # Development build with hot reload
    container_name: node-pulse-flagship
    env_file:
      - .env
    ports:
      - "8000:8000" # Laravel dev server
      - "5173:5173" # Vite dev server
      - "9003:9003" # Xdebug port
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
      flagship-migrate:
        condition: service_completed_successfully
      submarines-ingest:
        condition: service_started
    volumes:
      - ./flagship:/var/www/html # Mount entire app for hot reload
      - ./logs/flagship:/var/www/html/storage/logs
    networks:
      - node-pulse-admiral

  # Next.js Cruiser - Public Site
  cruiser:
    build:
      context: ./cruiser
      dockerfile: Dockerfile
      target: development
    container_name: node-pulse-cruiser
    env_file:
      - .env
    environment:
      <<: *common-variables
    ports:
      - "3000:3000"
    depends_on:
      - submarines-ingest
      - postgres
    volumes:
      - ./cruiser:/app
      - /app/node_modules
      - /app/.next
    networks:
      - node-pulse-admiral

networks:
  node-pulse-admiral:
    driver: bridge
    name: node-pulse-admiral
