---
# Verify node_exporter installation and service

- name: Wait for node_exporter to be ready
  wait_for:
    host: "{{ node_exporter_listen_address }}"
    port: "{{ node_exporter_listen_port }}"
    delay: 2
    timeout: 30
    state: started

- name: Check node_exporter metrics endpoint
  uri:
    url: "http://{{ node_exporter_listen_address }}:{{ node_exporter_listen_port }}/metrics"
    method: GET
    status_code: 200
    return_content: yes
  register: node_exporter_metrics_check
  retries: 3
  delay: 5

- name: Verify node_exporter is returning metrics
  assert:
    that:
      - node_exporter_metrics_check.status == 200
      - "'node_' in node_exporter_metrics_check.content"
      - "'# HELP' in node_exporter_metrics_check.content"
      - "'# TYPE' in node_exporter_metrics_check.content"
    fail_msg: "❌ Node Exporter metrics endpoint is not returning valid Prometheus metrics"
    success_msg: "✅ Node Exporter is running and exposing metrics successfully"

- name: Display node_exporter service status
  debug:
    msg: "✅ Node Exporter v{{ node_exporter_version }} is installed and running on {{ node_exporter_listen_address }}:{{ node_exporter_listen_port }}"
