---
# Ansible Playbook: Deploy process_exporter to servers
#
# Usage:
#   ansible-playbook playbooks/prometheus/deploy-process-exporter.yml -i inventory.yml
#
# This playbook:
# 1. Installs process_exporter on target servers
# 2. Configures process grouping by command name
# 3. Sets up systemd service (localhost:9256)
# 4. Verifies metrics endpoint is accessible
#
# Prerequisites:
# - Target servers must be accessible via SSH
# - User must have sudo privileges
#
# Note:
# - This playbook ONLY deploys process_exporter
# - To enable in agent, use: playbooks/nodepulse/enable-exporter.yml
# - Or use wrapper: playbooks/prometheus/deploy-process-monitoring.yml

- name: Deploy process_exporter to servers
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: process-exporter
      tags: ['process-exporter']

  post_tasks:
    - name: Display process_exporter status
      debug:
        msg: |
          ✓ process_exporter deployed successfully on {{ inventory_hostname }}!

          Metrics endpoint: http://127.0.0.1:9256/metrics
          Service status: systemctl status process_exporter
          View metrics: curl http://localhost:9256/metrics | grep namedprocess

          Next steps:
          1. Enable in agent: ansible-playbook playbooks/nodepulse/enable-exporter.yml -i inventory.yml \
               -e exporter_name=process_exporter -e exporter_endpoint=http://127.0.0.1:9256/metrics
          2. Verify data in database: SELECT COUNT(*) FROM admiral.process_snapshots;
      tags: ['always']
