---
- name: Retry Deployment on Failed Servers
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    # Agent version (GitHub release tag)
    agent_version: "{{ agent_version | default('latest') }}"

    # GitHub repository configuration
    agent_github_owner: "node-pulse"
    agent_github_repo: "agent"

    # Installation paths
    agent_install_dir: "/opt/nodepulse"
    agent_config_dir: "/etc/nodepulse"
    agent_data_dir: "/var/lib/nodepulse"
    agent_log_dir: "/var/log/nodepulse"

    # Ingest endpoint - passed from Laravel job via extra vars
    ingest_endpoint: "{{ ingest_endpoint }}"

    # Agent behavior (defaults)
    agent_interval: "{{ agent_interval | default('15s') }}"
    agent_timeout: "{{ agent_timeout | default('5s') }}"

    # Increase retries for failed servers
    max_retries: 5
    retry_delay: 10

  pre_tasks:
    - name: Display retry information
      debug:
        msg: |
          Retrying deployment on {{ inventory_hostname }}
          Attempt: {{ ansible_loop.index | default(1) }}
          Max Retries: {{ max_retries }}

  roles:
    - role: ../../roles/nodepulse-agent

  tasks:
    - name: Verify final status
      command: systemctl is-active nodepulse
      register: final_status
      changed_when: false
      failed_when: false

    - name: Mark as successful
      debug:
        msg: "Retry successful on {{ inventory_hostname }}"
      when: final_status.rc == 0

    - name: Mark as still failed
      fail:
        msg: "Retry failed on {{ inventory_hostname }}"
      when: final_status.rc != 0
