---
- name: Rollback Node Pulse Agent to Previous Version
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    agent_install_dir: "/opt/nodepulse"
    agent_backup_dir: "/opt/nodepulse/backups"
    previous_version: "{{ rollback_version | default('previous') }}"

  tasks:
    - name: Check if backup exists
      stat:
        path: "{{ agent_backup_dir }}/nodepulse.{{ previous_version }}"
      register: backup_file

    - name: Fail if backup not found
      fail:
        msg: "Backup version {{ previous_version }} not found"
      when: not backup_file.stat.exists

    - name: Stop current agent
      systemd:
        name: nodepulse
        state: stopped

    - name: Backup current binary
      copy:
        src: "{{ agent_install_dir }}/nodepulse"
        dest: "{{ agent_install_dir }}/nodepulse.failed"
        remote_src: yes
        owner: nodepulse
        group: nodepulse
        mode: "0755"

    - name: Restore previous version
      copy:
        src: "{{ agent_backup_dir }}/nodepulse.{{ previous_version }}"
        dest: "{{ agent_install_dir }}/nodepulse"
        remote_src: yes
        owner: nodepulse
        group: nodepulse
        mode: "0755"

    - name: Start agent with previous version
      systemd:
        name: nodepulse
        state: started

    - name: Verify agent is running
      command: systemctl is-active nodepulse
      register: agent_status
      changed_when: false

    - name: Display rollback result
      debug:
        msg: "Successfully rolled back to version {{ previous_version }}"
