---
#
# NodePulse Agent - Complete Uninstall Playbook
#
# This playbook completely removes the NodePulse agent from target servers.
# It stops the service, removes all files, and cleans up systemd units.
#
# Usage:
#   ansible-playbook -i inventory.yml uninstall-agent.yml
#
#   # Uninstall from specific host
#   ansible-playbook -i inventory.yml uninstall-agent.yml --limit web-01
#
#   # Dry run (check mode)
#   ansible-playbook -i inventory.yml uninstall-agent.yml --check
#
# Options:
#   - keep_config: Preserve configuration and server_id (default: false)
#   - keep_logs: Preserve log files (default: false)
#

- name: Uninstall NodePulse Agent
  hosts: all
  become: true
  gather_facts: false

  vars:
    # Set to true to keep configuration files
    keep_config: false
    # Set to true to keep log files
    keep_logs: false

  tasks:
    - name: Find pulse binary location
      ansible.builtin.command: which pulse
      register: pulse_location
      failed_when: false
      changed_when: false

    - name: Set pulse binary path
      ansible.builtin.set_fact:
        pulse_path: "{{ pulse_location.stdout | default('/usr/local/bin/pulse') }}"
        pulse_exists: "{{ pulse_location.rc == 0 }}"

    - name: Display uninstallation mode
      ansible.builtin.debug:
        msg: |
          Uninstalling NodePulse Agent from {{ inventory_hostname }}
          Binary location: {{ pulse_path }}
          Keep config: {{ keep_config }}
          Keep logs: {{ keep_logs }}
      when: pulse_exists

    - name: Stop NodePulse service using pulse command (if installed as service)
      ansible.builtin.command: "{{ pulse_path }} service stop"
      ignore_errors: true
      changed_when: false
      when: pulse_exists

    - name: Fallback - Stop NodePulse service via systemctl
      ansible.builtin.systemd:
        name: node-pulse
        state: stopped
      ignore_errors: true
      when: pulse_exists

    - name: Stop NodePulse daemon (if running via PID file)
      ansible.builtin.shell: |
        if [ -f /tmp/nodepulse.pid ]; then
          kill $(cat /tmp/nodepulse.pid) 2>/dev/null || true
          rm -f /tmp/nodepulse.pid
        fi
      args:
        executable: /bin/bash
      ignore_errors: true
      when: pulse_exists

    - name: Stop and disable auto-updater timer
      ansible.builtin.systemd:
        name: node-pulse-updater.timer
        state: stopped
        enabled: false
      ignore_errors: true
      when: pulse_exists

    - name: Disable NodePulse service
      ansible.builtin.systemd:
        name: node-pulse
        enabled: false
      ignore_errors: true
      when: pulse_exists

    - name: Remove systemd service files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/systemd/system/node-pulse.service
        - /etc/systemd/system/node-pulse-updater.service
        - /etc/systemd/system/node-pulse-updater.timer
      when: pulse_exists

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true
      when: pulse_exists

    - name: Remove pulse binary
      ansible.builtin.file:
        path: "{{ pulse_path }}"
        state: absent
      when: pulse_exists

    - name: Remove configuration directory (unless keep_config=true)
      ansible.builtin.file:
        path: /etc/node-pulse
        state: absent
      when:
        - pulse_exists
        - not keep_config

    - name: Remove data directory (unless keep_config=true)
      ansible.builtin.file:
        path: /var/lib/node-pulse
        state: absent
      when:
        - pulse_exists
        - not keep_config

    - name: Remove log directory (unless keep_logs=true)
      ansible.builtin.file:
        path: /var/log/node-pulse
        state: absent
      when:
        - pulse_exists
        - not keep_logs

    - name: Remove PID file (if exists)
      ansible.builtin.file:
        path: /tmp/nodepulse.pid
        state: absent
      when: pulse_exists

    - name: Display completion message
      ansible.builtin.debug:
        msg: |
          NodePulse agent successfully uninstalled from {{ inventory_hostname }}
          {% if keep_config %}Configuration preserved in /etc/node-pulse{% endif %}
          {% if keep_logs %}Logs preserved in /var/log/node-pulse{% endif %}
      when: pulse_exists

    - name: Display skip message
      ansible.builtin.debug:
        msg: "NodePulse agent not found on {{ inventory_hostname }}, skipping"
      when: not pulse_exists

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
