---
#
# NodePulse Agent v2.0 - Complete Uninstall Playbook
#
# This playbook completely removes the NodePulse agent from target servers.
# It stops the service, removes all files, and cleans up systemd units.
#
# Usage:
#   ansible-playbook -i inventory.yml uninstall-agent.yml
#
#   # Uninstall from specific host
#   ansible-playbook -i inventory.yml uninstall-agent.yml --limit web-01
#
#   # Dry run (check mode)
#   ansible-playbook -i inventory.yml uninstall-agent.yml --check
#
# Options:
#   - keep_config: Preserve configuration and server_id (default: false)
#   - keep_logs: Preserve log files (default: false)
#   - keep_buffer: Preserve buffered metrics (default: false)
#

- name: Uninstall NodePulse Agent v2.0
  hosts: all
  become: true
  gather_facts: false

  vars:
    # Set to true to keep configuration files
    keep_config: false
    # Set to true to keep log files
    keep_logs: false
    # Set to true to keep buffered metrics
    keep_buffer: false
    # Installation directories
    agent_install_dir: "/opt/nodepulse"
    agent_config_dir: "/etc/nodepulse"
    agent_data_dir: "/var/lib/nodepulse"
    agent_log_dir: "/var/log/nodepulse"

  tasks:
    - name: Check if nodepulse binary exists
      ansible.builtin.stat:
        path: "{{ agent_install_dir }}/nodepulse"
      register: nodepulse_binary

    - name: Display uninstallation mode
      ansible.builtin.debug:
        msg: |
          Uninstalling NodePulse Agent v2.0 from {{ inventory_hostname }}
          Binary location: {{ agent_install_dir }}/nodepulse
          Keep config: {{ keep_config }}
          Keep logs: {{ keep_logs }}
          Keep buffer: {{ keep_buffer }}
      when: nodepulse_binary.stat.exists

    - name: Stop nodepulse service
      ansible.builtin.systemd:
        name: nodepulse
        state: stopped
      ignore_errors: true
      when: nodepulse_binary.stat.exists

    - name: Disable nodepulse service
      ansible.builtin.systemd:
        name: nodepulse
        enabled: false
      ignore_errors: true
      when: nodepulse_binary.stat.exists

    - name: Remove systemd service file
      ansible.builtin.file:
        path: /etc/systemd/system/nodepulse.service
        state: absent
      when: nodepulse_binary.stat.exists

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true
      when: nodepulse_binary.stat.exists

    - name: Remove nodepulse binary
      ansible.builtin.file:
        path: "{{ agent_install_dir }}/nodepulse"
        state: absent
      when: nodepulse_binary.stat.exists

    - name: Remove installation directory
      ansible.builtin.file:
        path: "{{ agent_install_dir }}"
        state: absent
      when: nodepulse_binary.stat.exists

    - name: Remove logrotate configuration
      ansible.builtin.file:
        path: /etc/logrotate.d/nodepulse
        state: absent
      when: nodepulse_binary.stat.exists

    # Conditional removal based on flags
    - name: Remove configuration directory (unless keep_config=true)
      ansible.builtin.file:
        path: "{{ agent_config_dir }}"
        state: absent
      when:
        - nodepulse_binary.stat.exists
        - not keep_config

    - name: Remove buffer directory (unless keep_buffer=true or keep_config=true)
      ansible.builtin.file:
        path: "{{ agent_data_dir }}/buffer"
        state: absent
      when:
        - nodepulse_binary.stat.exists
        - not keep_buffer
        - not keep_config

    - name: Remove data directory (unless keep_config=true)
      ansible.builtin.file:
        path: "{{ agent_data_dir }}"
        state: absent
      when:
        - nodepulse_binary.stat.exists
        - not keep_config

    - name: Remove log directory (unless keep_logs=true)
      ansible.builtin.file:
        path: "{{ agent_log_dir }}"
        state: absent
      when:
        - nodepulse_binary.stat.exists
        - not keep_logs

    - name: Remove nodepulse system user
      ansible.builtin.user:
        name: nodepulse
        state: absent
        remove: yes
      when: nodepulse_binary.stat.exists

    - name: Remove nodepulse system group
      ansible.builtin.group:
        name: nodepulse
        state: absent
      when: nodepulse_binary.stat.exists

    - name: Display completion message
      ansible.builtin.debug:
        msg: |
          ✓ NodePulse agent v2.0 successfully uninstalled from {{ inventory_hostname }}
          {% if keep_config %}  Configuration preserved in {{ agent_config_dir }}{% endif %}
          {% if keep_logs %}  Logs preserved in {{ agent_log_dir }}{% endif %}
          {% if keep_buffer %}  Buffered metrics preserved in {{ agent_data_dir }}/buffer{% endif %}
      when: nodepulse_binary.stat.exists

    - name: Display skip message
      ansible.builtin.debug:
        msg: "NodePulse agent not found on {{ inventory_hostname }}, skipping"
      when: not nodepulse_binary.stat.exists
