---
- name: Deploy Node Pulse Agent
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    # Agent version (GitHub release tag)
    agent_version: "{{ agent_version | default('latest') }}"

    # GitHub repository configuration
    agent_github_owner: "node-pulse"
    agent_github_repo: "agent"

    # Installation paths
    agent_install_dir: "/opt/nodepulse"
    agent_config_dir: "/etc/nodepulse"
    agent_data_dir: "/var/lib/nodepulse"
    agent_log_dir: "/var/log/nodepulse"

    # Ingest endpoint - passed from Laravel job via extra vars
    ingest_endpoint: "{{ ingest_endpoint }}"

    # Agent behavior (defaults)
    agent_interval: "{{ agent_interval | default('15s') }}"
    agent_timeout: "{{ agent_timeout | default('5s') }}"

  pre_tasks:
    - name: Display deployment information
      debug:
        msg: |
          Deploying Node Pulse Agent to {{ inventory_hostname }}
          Ingest Endpoint: {{ ingest_endpoint }}

    - name: Ensure server is reachable
      wait_for_connection:
        timeout: 30
      register: connection_test
      ignore_errors: yes

    - name: Fail if server is unreachable
      fail:
        msg: "Server {{ inventory_hostname }} is unreachable"
      when: connection_test is failed

    - name: Install NTP for clock synchronization
      apt:
        name: ntp
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install chrony for clock synchronization (RHEL/CentOS)
      yum:
        name: chrony
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure NTP service is running and enabled (Debian/Ubuntu)
      systemd:
        name: ntp
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Ensure chrony service is running and enabled (RHEL/CentOS)
      systemd:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Wait for NTP to sync (may take a few seconds)
      pause:
        seconds: 5

    - name: Check NTP sync status (Debian/Ubuntu)
      command: timedatectl
      register: timedatectl_output
      changed_when: false

    - name: Display NTP sync status
      debug:
        msg: "{{ timedatectl_output.stdout_lines }}"

  roles:
    - role: ../../roles/nodepulse-agent

  post_tasks:
    - name: Verify agent is running
      systemd:
        name: nodepulse
        state: started
        enabled: yes
      register: agent_status

    - name: Display deployment summary
      debug:
        msg: |
          ✓ Agent deployed successfully to {{ inventory_hostname }}
          ✓ Service is {{ agent_status.status.ActiveState }}
          ✓ Enabled at boot: {{ agent_status.status.UnitFileState }}
