---
- name: Deploy Node Pulse Agent
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    # Agent version (GitHub release tag)
    agent_version: "{{ agent_version | default('latest') }}"

    # GitHub repository configuration
    agent_github_owner: "node-pulse"
    agent_github_repo: "agent"

    # Installation paths
    agent_install_dir: "/opt/nodepulse"
    agent_config_dir: "/etc/nodepulse"
    agent_data_dir: "/var/lib/nodepulse"
    agent_log_dir: "/var/log/nodepulse"

    # Ingest endpoint - passed from Laravel job via extra vars
    ingest_endpoint: "{{ ingest_endpoint }}"

    # Agent behavior (defaults)
    agent_interval: "{{ agent_interval | default('15s') }}"
    agent_timeout: "{{ agent_timeout | default('5s') }}"

  pre_tasks:
    - name: Display deployment information
      debug:
        msg: |
          Deploying Node Pulse Agent to {{ inventory_hostname }}
          Ingest Endpoint: {{ ingest_endpoint }}

    - name: Ensure server is reachable
      wait_for_connection:
        timeout: 30
      register: connection_test
      ignore_errors: yes

    - name: Fail if server is unreachable
      fail:
        msg: "Server {{ inventory_hostname }} is unreachable"
      when: connection_test is failed

  roles:
    - role: ../../roles/nodepulse-agent

  post_tasks:
    - name: Verify agent is running
      systemd:
        name: nodepulse
        state: started
        enabled: yes
      register: agent_status

    - name: Display deployment summary
      debug:
        msg: |
          ✓ Agent deployed successfully to {{ inventory_hostname }}
          ✓ Service is {{ agent_status.status.ActiveState }}
          ✓ Enabled at boot: {{ agent_status.status.UnitFileState }}
