---
# Common role metadata
galaxy_info:
  author: Node Pulse Team
  description: Shared tasks and utilities for Node Pulse roles
  company: Node Pulse
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - '8'
        - '9'

dependencies: []
