---
- name: Detect CPU architecture
  set_fact:
    agent_arch: >-
      {{
        'amd64' if ansible_architecture == 'x86_64'
        else 'arm64' if ansible_architecture == 'aarch64'
        else 'unknown'
      }}

- name: Fail if unsupported architecture
  fail:
    msg: |
      ❌ UNSUPPORTED ARCHITECTURE: {{ ansible_architecture }}

      Node Pulse Agent only supports 64-bit systems:
        ✓ x86_64 (64-bit Intel/AMD)
        ✓ aarch64 (64-bit ARM - AWS Graviton, etc.)

      32-bit systems (i386, i686, armv7l) are NOT supported.
      Please upgrade to a 64-bit operating system.
  when: agent_arch == 'unknown'

- name: Determine archive filename
  set_fact:
    archive_filename: "nodepulse-{{ agent_version }}-linux-{{ agent_arch }}.tar.gz"
    archive_url: "{{ agent_download_url }}/nodepulse-{{ agent_version }}-linux-{{ agent_arch }}.tar.gz"

- name: Download Node Pulse agent archive
  get_url:
    url: "{{ archive_url }}"
    dest: "/tmp/{{ archive_filename }}"
    mode: "0644"
    force: yes
    timeout: 120
  register: download_result
  retries: 3
  delay: 5
  until: download_result is succeeded

- name: Extract agent archive to temporary location
  unarchive:
    src: "/tmp/{{ archive_filename }}"
    dest: "/tmp"
    remote_src: yes

- name: Copy binary to installation directory
  copy:
    src: "/tmp/nodepulse"
    dest: "{{ agent_install_dir }}/nodepulse"
    remote_src: yes
    owner: nodepulse
    group: nodepulse
    mode: "0755"
  notify: restart nodepulse

- name: Clean up extracted files
  file:
    path: "/tmp/{{ item }}"
    state: absent
  loop:
    - nodepulse
    - README.md
    - nodepulse.yml
  ignore_errors: yes

- name: Clean up downloaded archive
  file:
    path: "/tmp/{{ archive_filename }}"
    state: absent

- name: Verify binary is executable
  command: "{{ agent_install_dir }}/nodepulse --version"
  register: version_check
  changed_when: false
  failed_when: version_check.rc != 0

- name: Display agent version
  debug:
    msg: "Downloaded Node Pulse Agent: {{ version_check.stdout }}"
