---
- name: Detect CPU architecture
  set_fact:
    agent_arch: >-
      {{
        'amd64' if ansible_architecture == 'x86_64'
        else 'arm64' if ansible_architecture == 'aarch64'
        else 'unknown'
      }}

- name: Fail if unsupported architecture
  fail:
    msg: |
      ❌ UNSUPPORTED ARCHITECTURE: {{ ansible_architecture }}

      Node Pulse Agent only supports 64-bit systems:
        ✓ x86_64 (64-bit Intel/AMD)
        ✓ aarch64 (64-bit ARM - AWS Graviton, etc.)

      32-bit systems (i386, i686, armv7l) are NOT supported.
      Please upgrade to a 64-bit operating system.
  when: agent_arch == 'unknown'

- name: Determine binary URL
  set_fact:
    binary_url: "{{ agent_download_url }}/nodepulse-linux-{{ agent_arch }}"

- name: Download Node Pulse agent binary
  get_url:
    url: "{{ binary_url }}"
    dest: "{{ agent_install_dir }}/nodepulse"
    mode: "0755"
    owner: nodepulse
    group: nodepulse
    force: yes
    timeout: 120
  register: download_result
  retries: 3
  delay: 5
  until: download_result is succeeded

- name: Verify binary is executable
  command: "{{ agent_install_dir }}/nodepulse --version"
  register: version_check
  changed_when: false
  failed_when: version_check.rc != 0

- name: Display agent version
  debug:
    msg: "Downloaded Node Pulse Agent: {{ version_check.stdout }}"
