---
# Verify system prerequisites first (from common role)
- import_role:
    name: common
    tasks_from: prerequisite

- name: Check if OS-specific variables file exists
  stat:
    path: "{{ role_path }}/vars/{{ ansible_os_family }}.yml"
  register: os_vars_file
  delegate_to: localhost

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  when: os_vars_file.stat.exists

- name: Create nodepulse user
  user:
    name: nodepulse
    system: yes
    create_home: no
    shell: /usr/sbin/nologin
    comment: "Node Pulse Agent Service User"

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: nodepulse
    group: nodepulse
    mode: "0755"
  loop:
    - "{{ agent_install_dir }}"
    - "{{ agent_config_dir }}"
    - "{{ agent_data_dir }}"
    - "{{ agent_log_dir }}"
    - "{{ agent_data_dir }}/buffer"

- import_tasks: download.yml
- import_tasks: configure.yml
- import_tasks: install.yml
- import_tasks: verify.yml
