---
# Verify system prerequisites for Node Pulse roles
# This task can be imported by any role to ensure the target server meets minimum requirements

- name: Verify system prerequisites
  assert:
    that:
      - ansible_facts.python_version is defined
      - ansible_facts.python.version.major >= 3 or (ansible_facts.python.version.major == 2 and ansible_facts.python.version.minor >= 7)
      - ansible_facts.service_mgr == 'systemd'
    fail_msg: |
      ❌ SYSTEM REQUIREMENTS NOT MET

      Node Pulse requires:
        ✓ Python 2.7+ or Python 3.5+
        ✓ systemd (for service management)

      Detected:
        • Python: {{ ansible_facts.python.version.major }}.{{ ansible_facts.python.version.minor }}
        • Service Manager: {{ ansible_facts.service_mgr }}
        • OS: {{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}

      Please upgrade your system to meet these requirements.
    success_msg: "✓ System requirements met (Python {{ ansible_facts.python.version.major }}.{{ ansible_facts.python.version.minor }}, systemd)"
