---
# Configure node_exporter

- name: Ensure textfile collector directory exists
  file:
    path: "{{ node_exporter_textfile_dir }}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: "0755"

- name: Start node_exporter service
  systemd:
    name: node_exporter
    state: started
    enabled: yes
