---
# Install node_exporter binary and systemd service

- name: Create symlink to node_exporter binary
  file:
    src: "{{ node_exporter_install_dir }}/node_exporter"
    dest: "{{ node_exporter_bin_path }}"
    state: link
    owner: root
    group: root
  when: node_exporter_needs_install
  notify: restart node_exporter

- name: Copy node_exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload systemd
    - restart node_exporter

- name: Enable node_exporter service
  systemd:
    name: node_exporter
    enabled: yes
    daemon_reload: yes
