---
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable nodepulse service
  systemd:
    name: nodepulse
    enabled: yes

- name: Start nodepulse service
  systemd:
    name: nodepulse
    state: started
  register: service_start

- name: Wait for service to be active
  wait_for:
    timeout: 10
  when: service_start.changed

- name: Check service status
  systemd:
    name: nodepulse
  register: service_status

- name: Display service status
  debug:
    msg: |
      Service Status: {{ service_status.status.ActiveState }}
      PID: {{ service_status.status.MainPID | default('N/A') }}
