---
# Verify node_exporter is available (required for simplified metrics)
- name: Check if node_exporter is running
  command: systemctl is-active node_exporter
  register: node_exporter_active
  changed_when: false
  failed_when: false

- name: Test node_exporter metrics endpoint
  uri:
    url: "http://127.0.0.1:9100/metrics"
    return_content: no
    status_code: 200
  register: node_exporter_metrics
  failed_when: false
  changed_when: false

- name: Display node_exporter status
  debug:
    msg: |
      node_exporter Status: {{ node_exporter_active.stdout | default('not found') }}
      Metrics Endpoint: {{ 'accessible' if node_exporter_metrics.status == 200 else 'NOT accessible' }}

- name: Warning if node_exporter is not available
  debug:
    msg: |
      ⚠️  WARNING: node_exporter is not running or not accessible!

      The Node Pulse Agent requires node_exporter to collect system metrics.
      Without it, the agent will not be able to scrape metrics.

      To fix this, run:
      ansible-playbook deploy-node-exporter.yml -i inventory.yml --limit {{ inventory_hostname }}
  when: node_exporter_active.rc != 0 or node_exporter_metrics.status != 200

# Verify agent is running
- name: Check if agent is running
  command: systemctl is-active nodepulse
  register: agent_active
  changed_when: false
  failed_when: false

- name: Verify agent process
  command: pgrep -f nodepulse
  register: agent_process
  changed_when: false
  failed_when: false

- name: Check agent logs for errors
  shell: journalctl -u nodepulse --since "1 minute ago" --no-pager | grep -i error || true
  register: agent_errors
  changed_when: false

- name: Check agent logs for successful metrics scraping
  shell: journalctl -u nodepulse --since "1 minute ago" --no-pager | grep -i "scraped\|metrics\|prometheus" | tail -5 || true
  register: agent_metrics_logs
  changed_when: false

- name: Display verification results
  debug:
    msg: |
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      Verification Results for {{ inventory_hostname }}
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

      node_exporter:
        Status: {{ node_exporter_active.stdout | default('not found') }}
        Metrics: {{ 'accessible' if node_exporter_metrics.status == 200 else 'NOT accessible' }}

      Agent:
        Status: {{ agent_active.stdout }}
        Process ID: {{ agent_process.stdout | default('Not Running') }}
        Recent Errors: {{ agent_errors.stdout_lines | length }} errors found

      Recent Activity:
      {{ agent_metrics_logs.stdout_lines | join('\n      ') if agent_metrics_logs.stdout_lines else '  (No recent scrape activity logged)' }}

      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

- name: Fail if agent is not running
  fail:
    msg: "Agent is not running on {{ inventory_hostname }}"
  when: agent_active.rc != 0
